name: SignPortal
api: [3.0.0]
version: 1.1.4
load: POSTWORLD
main: leonchang99\SignPortal\Main
author: 99leonchang
website: https://github.com/99leonchang/SignPortal

commands:
 generate:
  description: Generate new world (testing only)
  usage: "Usage: /generate <worldname>"
  permission: signportal.command.generate

permissions:
 signportal.command.generate:
  description: "Allows the user to run the generate command"
  default: op
 signportal.create:
  description: "Allows the user to create SignPortals"
  default: op